### ISSUE TITLE
Automated freeze / timeout (and whitelist to prevent)

### ISSUE THREAD

**Issue by rayman89** [freddyb/webext-discard-tab#3]
Could you consider adding automatic unloading of tabs after x minuted of tab not being used and a whitelist to be able to prevent some tabs to being unloaded? If you can please add the option to whitelist a page from the context menu and support subdomains so for example on right click on the tabs besides freeze tab it would be nice to have whitelist this domain (ex youtube.com) and on the options when you acces the whitelist it could be nice to be able to edit it to for example https://www.youtube.com/user/xxxxxx/ or https://www.youtube.com/user/* or https://www.youtube.com/results?search_query=*

**Comment by freddyb** [comment]
Great idea. I will add this to my queue, but will also allow pull requests.
This sounds straightforward, but someone picking this up should consult me on an implementation plan in this issue before submitting a pull request.

**Comment by rayman89** [comment]
Thanks for having my suggestions into account.

**Comment by freddyb** [comment]
wontfixing this, see #4
