### ISSUE TITLE
Type error for parameter updateProperties (Unexpected property "title") for tabs.update

### ISSUE THREAD

**Issue by DennisGaida** [freddyb/webext-discard-tab#5]
Tried FF beta & nightly (59.0a1), but get the error "Type error for parameter updateProperties (Unexpected property "title") for tabs.update" in debug log. I suppose this is due to a missing permission? 

> The tabs.Tab object doesn't contain url, title and favIconUrl unless the "tabs" permission has been requested.
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/update

**Comment by freddyb** [comment]
Ah yeah. Thanks for reporting @moontear.
I'll have to request the tabs permission or just not update the title.
I'm leaning toward the latter. Will make an attempt later.
