### ISSUE TITLE
Drop use of open_in_tab if possible

### ISSUE THREAD

**Issue by Rob--W** [freddyb/webext-discard-tab#8]
This is a follow-up to https://github.com/freddyb/webext-discard-tab/pull/7#discussion_r180191638

The referenced bug, https://bugzilla.mozilla.org/show_bug.cgi?id=1382953 has been fixed in Firefox 61 and might be uplifted to Firefox 60.

Once the decision has been made, ideally the `open_in_tab` key should be removed from manifest.json, so that the preferences are displayed inline. For backwards-compatibility, options.html/js can open the new tab if it detects that the permissions API call fails.

https://github.com/freddyb/webext-discard-tab/blob/76cc4c5aaa17691073cd95a9cb9714f25647bbf9/manifest.json#L27

**Comment by mozfreddyb** [comment]
@Rob--W I noticed that this is still open, though the depending bug in Bugzilla has since been closed. Would you be willing to take this?
