### ISSUE TITLE
Sometimes when I choose to Discard a pinned tab, the tab gets reloaded instead

### ISSUE THREAD

**Issue by mnoorenberghe** [freddyb/webext-discard-tab#9]
I haven't figured out the pattern yet but sometimes when I choose to discard a pinned tab via the tab's context menu, the tab simply reloads instead of being discarded.

**Comment by freddyb** [comment]
Hm, can't think of a good reason from the top of my head.
I'll take a look at the implementation of `discard()`, maybe I need to do something special for pinned tabs?

thanks for reporting, Matt!

**Comment by freddyb** [comment]
@mnoorenberghe Do you still have problems with discarding pinned tabs? It's working well for me, so I consider closing this issue.

**Comment by mnoorenberghe** [comment]
I honestly stopped using the feature because of a different bug that would cause the tab to hang and not be recoverable (usually showing a tab spinner).
